settings:
  readme_file: "./README.md"
  disabled_events:
    - "comments"

  date:
    timezone: "America/Barbados"
    text: '<p align="center">Last refresh: <b>{DATE} IST</b>'
    commit_msg: "Ê•Ê˜Ì…ÍœÊ˜Ì…Ê” ğŸ”¥README UPDATEDğŸ”¥ Ê•Ê˜Ì…ÍœÊ˜Ì…Ê”"
messages:
  comments: "ğŸ’¬ Commented on {ID} in {REPO}"
  issue_opened: "â—ï¸ Opened issue {ID} in {REPO}"
  issue_closed: "âœ”ï¸ Closed issue {ID} in {REPO}"
  pr_opened: "ğŸ’ª Opened PR {ID} in {REPO}"
  pr_closed: "âŒ Closed PR {ID} in {REPO}"
  pr_merged: "ğŸ‰ Merged PR {ID} in {REPO}"
  create_repo: "ğŸ“” Created new repository {REPO}"
  fork_repo: "ğŸ”± Forked {FORK} from {REPO}"
  wiki_create: "ğŸ“– Created new wiki page {WIKI} in {REPO}"
  added_member: "ğŸ¤ Became collaborator on {REPO}"
  changes_approved: "ğŸ‘ Approved {ID} in {REPO}"
