settings:
  disabled_events: [event1, event2, event3]
  commit_msg: "âœŒÙ©(Ì¾â—Ì®Ì®ÌƒÌ¾â€¢ÌƒÌ¾)Û¶âœŒğŸ”¥â„ğ”¼ğ”¸ğ”»ğ•„ğ”¼ ğ•Œâ„™ğ”»ğ”¸ğ•‹ğ”¼ğ”»ğŸ”¥âœŒÙ©(Ì¾â—Ì®Ì®ÌƒÌ¾â€¢ÌƒÌ¾)Û¶âœŒ"
  max_lines: 0
  readme_file: "./README.md"
  date:
    timezone: "GMT-04:00"
    text: "<i>Last refresh</i>: <b>{DATE}</b>"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
