settings:
  disabled_events: [event1, event2, event3]
  commit_msg: "Ù©(Ì¾â—Ì®Ì®ÌƒÌ¾â€¢ÌƒÌ¾)Û¶ğŸ”¥â„ğ”¼ğ”¸ğ”»ğ•„ğ”¼ ğ•Œâ„™ğ”»ğ”¸ğ•‹ğ”¼ğ”»ğŸ”¥Ù©(Ì¾â—Ì®Ì®ÌƒÌ¾â€¢ÌƒÌ¾)Û¶"
  max_lines: 0
  readme_file: "./README.md"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT-04:00"
    text: "<i>Last refresh</i>: <b>{DATE}</b>"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
