name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: 
    branches: [ main ]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          committer_message: ðŸ“ˆGitHub action updated profile metricsðŸ“‰
          token: ${{ secrets.METRICS_TOKEN }}
          user: trinib
          base: header, activity, repositories
          plugin_fortune: yes
          plugin_introduction: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, comment, push, star
          plugin_gists: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: icons
          plugin_topics_limit: 15
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 800
          plugin_people_size: 28
